language: node_js
node_js:
  - "10"

install:
  - yarn --frozen-lockfile
script:
  - yarn docs:build
catche: yarn

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build
  repo: simonwong/simonwong.github.io
  target_branch: master
  on:
    branch: master
